language: python
python:
  - "3.4"
  - "3.5"
install:
  - gem install asciidoctor
  - pip install -r static_nikola_part/requirements.txt
  - pip install -r flask_application_part/pip_requirements.txt
script:
  - cd static_nikola_part && nikola build && nikola build
  - python -m pytest flask_application_part
