
////
.. title: ACCU 2018 Presenters
.. description: List of presenter bios with links to session blurbs.
.. type: text
////

[[XAlexVoicu]]
== Alex Voicu

link:sessions.html#XHCCBringingModernCtoaGPUNearYou[HCC: Bringing Modern C++ to a GPU Near You]

Alex is a Programmer on the HCC team at AMD, working primarily on the front-end and runtime components. He has been known to annoy his colleagues by insisting on strict adherence to the {cpp} Standard and an unnatural passion for generic programming. In the past he was a member of the Visual {cpp} Libraries team at Microsoft.


[[XAlisdairMeredith]]
== Alisdair Meredith

link:sessions.html#XTheIncredibleShrinkingStandard[The Incredible Shrinking Standard]

Alisdair Meredith is a software developer at BloombergLP in New York, and the {cpp} Standard Committee Library Working Group chair.

He has been an active member of the {cpp} committee for just over a decade, and by a lucky co-incidence his first meeting was the kick-off meeting for the project that would become {cpp}11, and also fixed the contents of the original library TR.

He is currently working on the BDE project, BloombergLP's open source libraries that offer a foundation for {cpp} development, including a standard library implementation supporting the polymorphic allocator model proposed for standardization.



[[XAnastasiaKazakova]]
== Anastasia Kazakova

link:sessions.html#XDebugCWithoutRunning[Debug C++ Without Running]

As a C and {cpp} software developer, Anastasia Kazakova created real-time *nix-based systems and pushed them to production for 8 years. She has a passion for networking algorithms and embedded programming and believes in good tooling. With all her love for {cpp}, she is now the Product Marketing Manager on the JetBrains CLion team. Besides, Anastasia runs a {cpp} user group in Saint-Petersburg, Russia (https://www.meetup.com/St-Petersburg-CPP-User-Group/).


[[XAndyBalaam]]
== Andy Balaam

link:sessions.html#XSchemeLispFeeltheCool[Scheme Lisp: Feel the Cool]

Andy Balaam loves code, and loves talking about code.  His blog, articles and open source projects can be found at artificialworlds.net and his videos are at youtube.com/ajbalaam


[[XAnthonyWilliams]]
== Anthony Williams

link:sessions.html#XDesigningmultithreadedcodeforscalability[Designing multithreaded code for scalability]

Anthony Williams is the author of {cpp} Concurrency in Action, and a UK-based developer, consultant and trainer with over 20 years of experience in {cpp}. He has been an active member of the BSI {cpp} Standards Panel since 2001, and is author or coauthor of many of the {cpp} Standards Committee papers that led up to the inclusion of the thread library in the {cpp}11 Standard. He continues to work on new facilities to enhance the {cpp} concurrency toolkit, both with standards proposals, and implementations of those facilities for the just::thread Pro extensions to the {cpp} thread library from Just Software Solutions Ltd. Anthony lives in the far west of Cornwall, England.


[[XArjanvanLeeuwen]]
== Arjan van Leeuwen

link:sessions.html#XHownottoleadateamofsoftwareprofessionals[How not to lead a team of software professionals]

Arjan van Leeuwen is a software developer and team lead at browser maker Opera Software, working on its eponymous web browser for desktop platforms, mostly in {cpp}. Reliability and speed are things that matter every day, but code quality is the subject that can really get him riled up. Arjan has worked on Opera Software's flagship product, the Opera browser for computers, for 10 years and has spoken regularly at ACCU conferences.


[[XArneMertz]]
== Arne Mertz

link:sessions.html#X100babystepsawayfromspaghetticode[100 baby steps away from spaghetti code]

link:sessions.html#XCodeReviewsWhyWhatandHow[Code Reviews: Why, What and How]

Arne Mertz works as an expert software engineer at Zühlke in Hamburg. Having suffered the horrors of legacy spaghetti enterprise {cpp} for several years, he now is a blogger and trainer for modern {cpp}, Clean Code, and software craftsmanship.


[[XAustinBingham]]
== Austin Bingham

link:sessions.html#XPythoncppIntegrationwithpybind11[Python/{cpp} Integration with pybind11]

Austin is a founding director of link:https://sixty-north.com[Sixty North], a software consulting, training,
and application development company. A native of Texas, in 2008 Austin moved to
Stavanger, Norway where he helped develop industry-leading oil reservoir
modeling software. Prior to that he worked at National Instruments, at Applied
Research Labs developing sonar systems, and at several telecommunications
companies. He is an experienced presenter, teacher, author, and active member of
the open source community. He’s the founder of Stavanger Software Developers, a
social software group in Stavanger. Austin holds a MSc in Computer Engineering
from the University of Texas at Austin. 


[[XBenjaminMisell]]
== Benjamin Misell 

link:sessions.html#XTalesofCthe6502andtheBBCwithaddedpython[Tales of C, the 6502 and the BBC (with added python)]

15 years old. Python coder for many years who likes to dabble in C and {cpp} for embedded machines (Arduino, MicroBit, Pebble etc). CTO and lead developer a company founded with friend Fluid Media. Open to as many ideas as can possibly fit in my head.


[[XBjörnFahller]]
== Björn Fahller

link:sessions.html#XHigherorderfunctionsfortherestofus[Higher order functions for the rest of us.]

link:sessions.html#XTypesafeCLOL[Type safe C++ – LOL! :-)]

Björn wrote his first program in 1980. After completing his MSc in CS and Engineering in 1994, programming has been the primary source of income, mostly from writing embedded software for communications systems. He has been working for a while at Net Insight, where he wears many hats, including mentor, trouble shooter, network communications expert, software architect and programmer; the latter in increasingly modern {cpp}.

Occasionally Björn has been seen tinkering with unorthodox software constructs, pondering "what can be done with this?" He lives in Stockholm.


[[XCharlesBailey]]
== Charles Bailey

link:sessions.html#XScriptingGit[Scripting Git]

Charles is a software developer at Bloomberg LP. He works in Developer Experience where he helps maintain and improve the tools used in development, and consult and advise on all aspects of software development.

His previous career in software has included roles in such diverse areas as web technology, business intelligence, data warehousing, defence and radar.

He understands the importance of optimal software practices and so has a keen interest in source control systems and best practices surrounding their use.

He is a Git user, advocate and contributor and relishes the opportunity to slice through knotty problems with his git-fu and to teach others how to do the same.


[[XCharleyBay]]
== Charley Bay

link:sessions.html#XAQuantumDataStructureForClassicalComputers[A Quantum Data Structure For Classical Computers]

Software developer with 25+ years experience in large-scale and distributed systems in performance-sensitive environments including real-time processing, performance visualization, embedded systems, time-sensitive processing of large data sets, hardware status-and-control, and instrument/process/sub-assembly monitoring. 



[[XChrisOldwood]]
== Chris Oldwood

link:sessions.html#XChrisandJezsOldSkoolArtisanSoftwareWorkshop[Chris and Jez's Old Skool Artisan Software Workshop]

link:sessions.html#XMonolithicDelivery[Monolithic Delivery]

Chris is a freelance programmer who started out as a bedroom coder in the 80's writing assembler on 8-bit micros. These days it’s enterprise grade technology in plush corporate offices. He also commentates on the Godmanchester duck race.


[[XChristopherSimons]]
== Christopher Simons

link:sessions.html#XSimplytheBestOptimisingwithanEvolutionaryComputingFramework[Simply the Best: Optimising with an Evolutionary Computing Framework]

After many years as a programmer, Chris now lectures at the University of the West of England, Bristol, in areas such as artificial intelligence and software development.  Chris is interested in how software can learn from people, and vice versa, for mutual learning.


[[XDanielJames]]
== Daniel James

link:sessions.html#XCryptographyforProgrammers[Cryptography for Programmers]

Daniel is a software designer and programmer working in Maidenhead, England. Since working on a contract for a large electronics company that sold commercial encryption hardware and services, thirty years ago, his work has almost always been concerned with one aspect or another of information security.


[[XDanieleProcida]]
== Daniele Procida

link:sessions.html#XFightingthecontrolstragedyandmadnessforpilotsandprogrammers[Fighting the controls: tragedy and madness for pilots and programmers]

I am a core developer of the Django project. I work at Divio, and live in Cardiff, where I help run things like PyDiff, PyCon Namibia and PyCon UK.

I'm heavily involved in the international Python/Django open-source software communities and have a special interest in open-source software development in Africa


[[XDetlefVollmann]]
== Detlef Vollmann

link:sessions.html#XFinallyExecutorsforC[Finally Executors for C++]

Detlef Vollmann has a background of more than 30 years in software engineering, about 25 years in object technology.
He is an active member of the {cpp} standardization committee 
 generally assigned to the concurrency sub-working group) and one of the (many) authors of the {cpp} performance report.  He designs and implements programs with and without concurrency since 1980.
He's currently independent, consulting and teaching courses on embedded systems, concurrency and object oriented technology.

Since 1991, he has authored and taught seminars, tutorials and short presentations about {cpp}, object-oriented technologies, software architecture, embedded design and distributed computing for major Swiss companies and at international conferences.


[[XDietmarKühl]]
== Dietmar Kühl

link:sessions.html#XConceptBasedTesting[Concept Based Testing]

Dietmar Kühl is a senior software developer at Bloomberg L.P. working
on the data distrubtion environment used both internally and
by enterprise installations at clients. Before joining Blooomberg
he has done mainly consulting for software projects in the
finance area. He is a regular attendee of the ANSI/ISO {cpp}
standards committee, presents at conferences, and he used to
be a moderator of the newsgroup comp.lang.c++.moderated. He
frequently answers questions on Stackoverflow.


[[XDmitryKandalov]]
== Dmitry Kandalov

link:sessions.html#XCoroutinesexplained[Coroutines explained]

https://twitter.com/dmitrykandalov[Dmitry] has been programming and trying to get better at it since DOS times.
He is currently working with Java and JVM languages such as http://kotlinlang.org[Kotlin].


[[XDomDavis]]
== Dom Davis

link:sessions.html#XGraphsFromNovicetoGraphanista[Graphs: From Novice to Graphanista]

Dom Davis is a veteran of The City and a casualty of The Financial Crisis. Not content with bringing the world to its knees he then went off to help break the internet before winding up in Norfolk where he messes about doing development and devops. Dom has been writing code since his childhood sometime in the last millennium – he hopes some day to become good at it.

Dom is an enthusiastic and impassioned speaker [read: he gabbles] who uses a blend of irreverent sarcasm and flippant humour to bring complex subjects to a broad audience. Whether or not they understand him is up for debate, but he likes to believe they do.


[[XDuyguCakmak]]
== Duygu Cakmak

link:sessions.html#XThemightychallengeofmodellinggeopoliticalbehaviourinTotalWarhowAIcandeliverentertainment[The mighty challenge of modelling geopolitical behaviour in Total War: how AI can deliver entertainment.]

Duygu is a software engineer with a Master’s degree in Artificial Intelligence. She has worked as an AI programmer at Creative Assembly for the last 2 years. Turning coffee and chocolate into realistic game AI for the Total war series is her speciality. 

As an AI programmer, she mainly works on writing new AI systems, new AI features for the Campaign and developing analysing and visualising tools for AI auto play tests. 

Not only does she love to code in her free time but she also enjoys the occasional video game as well as flightless penguins.



[[XEoinWoods]]
== Eoin Woods

link:sessions.html#XCommonWebappVulnerabilitiesandWhattoDoAboutThem[Common Webapp Vulnerabilities and What to Do About Them]

Eoin Woods is the CTO of Endava, a technology company that delivers projects in the areas of digital, agile and automation.  Prior to joining Endava, Eoin has worked in the software engineering industry for 20 years developing system software products and complex applications in the capital markets domain.  His main technical interests are software architecture, distributed systems and computer security. Eoin can be contacted via his web site at www.eoinwoods.info


[[XFelixPetriconi]]
== Felix Petriconi

link:sessions.html#XCanIchangemyorganisation[Can I change my organisation?]

link:sessions.html#XThereIsABetterFuture[There Is A Better Future]

Felix Petriconi is working as professional programmer since 1993 after he had finished his study of electrical engineering. He started his career as teacher for intellectually gifted children, freelance programmer among others in telecommunication and automotive projects. Since 2003 he is employed as programmer and development manager at the MeVis Medical Solutions AG in Bremen, Germany. He is part of a team that develops and maintains radiological medical devices. His focus is on {cpp} development, training of “modern” {cpp}, and application performance tuning. He is a regular speaker at the {cpp} user group in Bremen, a blog editor of https://isocpp.org and a member of the ACCU’s conference committee.



[[XFlorianGilcher]]
== Florian Gilcher

link:sessions.html#XConcurrencywithoutfearRust[Concurrency without fear: Rust]

link:sessions.html#XThreeyearsofRustAlookaround[Three years of Rust - A look around]

Florian Gilcher is a Rust trainer and member of the Rust community team. He owns a small company building and administrating backend systems. He runs the European Rust community conference, RustFest.

Before starting to work with Rust, he was heavily invested in the Ruby and used Rust to get back into systems programming.


[[XFrancesBuontempo]]
== Frances Buontempo

link:sessions.html#XSimplytheBestOptimisingwithanEvolutionaryComputingFramework[Simply the Best: Optimising with an Evolutionary Computing Framework]

link:sessions.html#XTurtlesHillclimbingHammersPaperbags[Turtles! Hill climbing! Hammers! Paper bags!]

Frances Buontempo is currently editor of the ACCU’s Overload magazine and is a researcher at City, University of London, working on a project to provide diversity enhancements to SIEMS (Security Information and Event Management) http://disiem-project.eu/.

After graduating from Leeds University with a B.A. in Mathematics and Philosophy, she worked as a mathematics and IT secondary school teacher, eventually ending up as a programmer. During this time she obtained an M.Sc. in Pure Mathematics with the Open University, and then returned to Leeds University, to study for a PhD in data mining to predict how toxic organic chemicals might be. Between then and now, she has worked in various companies in London with a finance focus.

She has talked and written about various ways to program your way out of a paper bag, providing a gentle introduction to some machine learning approaches, while trying to keep up to date with new techniques.


[[XGailOllis]]
== Gail Ollis

link:sessions.html#XWhatsnewaboutfakenews[What's new about fake news?]

Pythonista, cyberpsychology and programming lecturer, researcher in psychology of software development. Once upon a time, and for many years, I worked as a software developer. But people and computers are just too interesting a combination to study so there's no going back. I'm still programming, but now I have the luxury of writing only what I want to, with a clean slate. And in Python, of course!


[[XGenAshley]]
== Gen Ashley

link:sessions.html#XDiversityandInclusivityinTech[Diversity & Inclusivity in Tech]

Gen is the Director of https://www.womenwhocode.com/[Women Who Code London] and is a very active leader in
the tech community in London. Aside from her involvement with Women Who Code she is a Lead for
https://www.womentechmakers.com/[Google Women Techmakers London], https://2017.spaceappschallenge.org/[NASA
Space Apps Challenge London] and https://twittercommunity.com/[Twitter Developer Community London].  She is
also part of the leadership committee for http://adaslist.co/[Ada's List] (a network for women in
technology). She is co-organiser of http://coedco.de/[COED:CODE],
http://www.opentechschool.org/[OpenTechSchool London] and London Game Developers. She was the Head of
Developer Outreach at Skills Matter and a former VP/Business Development Manager/Project Manager at
Citigroup. In 2016 Gen helped lead Anita Borg Institute London and was actively instrumental in delivering
the very first 1-Day Grace Hopper Conference in Europe which was held in London.


[[XGiovanniAsproni]]
== Giovanni Asproni

link:sessions.html#XCreatinganIncrementalArchitectureforyourSystem[Creating an Incremental Architecture for your System]

Giovanni has worked in many roles in several application domains. After many years providing consulting, training and advice, as well as coding, to projects of all sizes, he joined Zuhlke Engineering in London where he works as a Principal Consultant.
He is a past Chair of the London XPDay and the ACCU conferences, and the Industry & Practice co-chair for XP2016. He is a member of the ACM and the IEEE Computer Society, and contributed to the book 97 Things Every Programmer Should Know, published by O'Reilly.


[[XGregLaw]]
== Greg Law

link:sessions.html#XLinuxUserKernelABItheoftensurprisingrealitiesofhowCandCprogramsreallytalktotheOS[Linux User/Kernel ABI: the often surprising realities of how C and C++ programs really talk to the OS]

Greg is the co-founder and CEO of Undo. He is a coder at heart, but likes to bridge the gap between the business and software worlds. (Sadly, these days most of Greg's coding is done on aeroplanes.)

Greg has over 20 years’ experience in the software industry and has held development and management roles at companies including the pioneering British computer firm Acorn, as well as fast-growing start ups, NexWave and Solarflare. It was at Acorn that Greg met Julian and on evenings and weekends, they invented the core technology that would eventually become Undo Live Recorder. Greg left Solarflare in 2012 to lead Undo as CEO and has overseen the company as it transitioned from the shed in his back garden to a scalable award-winning business.

Greg holds a PhD from City, University of London, that was nominated for the 2001 British Computer Society Distinguished Dissertation Award. He lives in Cambridge, UK with his wife Ali and children Abi and Sam. In his spare time Greg catches up on email.


[[XGuyDavidson]]
== Guy Davidson

link:sessions.html#XThemightychallengeofmodellinggeopoliticalbehaviourinTotalWarhowAIcandeliverentertainment[The mighty challenge of modelling geopolitical behaviour in Total War: how AI can deliver entertainment.]

Guy is heading for his 20th anniversary at Creative Assembly, and has just passed his 30th anniversary of {cpp} usage. He is a member of the ISO {cpp} committee and enjoys outreach to schools and universities.

In his bountiful spare time he works on a 2D graphics proposal for standard {cpp}, studies piano, raises teenagers and teaches Tai Chi.




[[XHadiHariri]]
== Hadi Hariri

link:sessions.html#XKotlinNativeEmbracingexistingecosystems[Kotlin/Native – Embracing existing ecosystems]

Developer and creator of many things OSS, his passions includes Web Development and Software
Architecture. Has authored a couple of books, a few courses and has been speaking at industry events for
over 15 years. Host to Talking Kotlin, he works at JetBrains leading the Developer Advocacy team, and spends
as much time as he can writing code.


[[XHubertMatthews]]
== Hubert Matthews

link:sessions.html#XReadandwriteconsideredharmful[Read and write considered harmful]

Hubert is an independent software consultant, architect and trainer based in Oxford. His work ranges from teaching and advising on software development in far-off places through to designing enterprise systems and government web sites. Hubert has been an ACCU member for many years and has presented regularly at its conferences as well as being a former chairman. In his abundant free time he claims to indulge in salsa, clay-pigeon shooting, organising rowing and driving too fast.


[[XJDanielGarcia]]
== J. Daniel Garcia

link:sessions.html#XParallelDesignPatternsandStreamParallelism[Parallel Design Patterns and Stream Parallelism]

J Daniel Garcia is an Associate Professor in Computer Architecture at University Carlos III of Madrid, Spain. He has been serving as head of the Spanish delegation to ISO {cpp} standards committee since 2008. Before joining academia he worked as a software engineer in industrial projects in different domains including real time control systems, civil engineering, medical imaging, aerospace engineering, and high performance scientific computing. He has led the participation of UC3M in the European projects REPARA and RePhrase, both of them highly related to the use of parallelism in {cpp}. His main research goal is to make software developer lives easier by balancing software maintainability and application performance. In summary easier to read, faster to run, and less resources consumed. He is also the chair of the successful using std::cpp conference in Spain that gathers every year around 180 spanish {cpp} developers.


[[XJeffreyMendelsohn]]
== Jeffrey Mendelsohn

link:sessions.html#XWouldreserveupgradedowngradeMethodsImprovestdshared_mutex[Would 'reserve'/'upgrade'/'downgrade' Methods Improve 'std::shared_mutex'?]

Jeffrey Mendelsohn is currently a Team Lead in a software infrastructure group at Bloomberg L.P.  Dr. Mendelsohn has worked previously as a high-frequency spread trader, as the CTO for Blue Fire Capital LLC, and as the CTO for Chopper Trading LLC.  His academic credentials include a Ph.D. in Computer and Information Science ('98), a MSE in Mechanical Engineering & Applied Mechanics ('96), a MSE in Computer & Information Science ('94), a BSE in Computer Science and Engineering ('93), and a BS in Economics ('93); all from the University of Pennsylvania.


[[XJezHiggins]]
== Jez Higgins

link:sessions.html#XChrisandJezsOldSkoolArtisanSoftwareWorkshop[Chris and Jez's Old Skool Artisan Software Workshop]

Jez Higgins is a jobbing programmer so dedicated to the cause of software craftsmanship he once cycled to the conference from Birmingham. He was the 2017 Player of the Season for Kings Heath Hockey Club Mens IIIs. He can be contacted for programming assistance or hockey coaching at @jezhiggins or jez@jezuk.co.uk.


[[XJohnLakos]]
== John Lakos

link:sessions.html#XCModulesandLargeScaleDevelopment[C++ Modules and Large Scale Development]

TBD, very similar to past, except book WILL be done in 2018!


[[XJonJagger]]
== Jon Jagger

link:sessions.html#XCCountdownPubQuiz[C++ Countdown Pub Quiz]

link:sessions.html#XTheongoingdesignandevolutionofcyberdojo[The ongoing design and evolution of cyber-dojo]

I’m a software consultant specializing in practice, process, test driven development, and complex-adaptive systems-thinking. Hire me! I’m 30 years old (hex) and I’ve loved software since I was 10 (decimal). I built cyber-dojo.org to promote deliberate practice for software developers. I’ve worked with Accenture, Aviva, Cisco, Ericsson, Friends Provident, HP, Microsoft, Opera, Ordnance Survey, RBS, Reuters, Renault F1, Schlumberger, Tandberg and many many more. If you don’t like my work I won’t invoice you. I’m the co-author (with Olve Maudal) of the Deep C/{cpp} slide deck (over 600,000 views) I’m the ex ECMA Task Group 2 C# convenor. I’ve had some C# books published. I’m the ex ACCU conference chairman. I’m married to the beautiful Natalie, and proud father of Ellie, Penny and Patrick. I love coarse fishing and salmon fishing. I live in Somerset, England. On twitter I’m @JonJagger


[[XJonKalb]]
== Jon Kalb

link:sessions.html#XCTodayTheBeastisBack[C++ Today: The Beast is Back]

Jon Kalb is a freelance {cpp} instructor and chairs {cpp}Now, CppCon, and the Boost Steering Committee. He has been programming in {cpp} for over 25 years and has written {cpp} for Amazon, Apple, Dow Chemical, Intuit, Lotus, Microsoft, Netscape, Sun, and Yahoo!


[[XJonathantheJPsterPallant]]
== Jonathan 'theJPster' Pallant

link:sessions.html#XGreaseAMessagePassingApproachtoProtocolStacksinRust[Grease: A Message-Passing Approach to Protocol Stacks in Rust]

Jonathan Pallant is a Senior Technical Consultant within Cambridge
Consultants' Wireless Embedded Software Department. Jonathan gained a First
in Computer Systems Engineering (MEng) from the University of Warwick in
2004 and then went straight into embedded systems research and development.
At Cambridge Consultants for almost nine years now, Jonathan has worked on
projects ranging from 8-bit micros to 'five-9s' teleco software running
across 14 blades, and everything in between. Since 2010 he has been an
architect and core developer for Cambridge Consultants' own in-house CI
system and also takes an active role in setting their software quality and
product development processes. Jonathan is a big fan of the Rust
programming language, and manages a number of published crates, including
for the https://crates.io/crates/stellaris-launchpad[Texas Instruments
Stellaris Launchpad devkit] and the
https://github.com/thejpster/pi-workshop-rs/[Raspberry Pi SenseHat]. You
can find Jonathan online through https://keybase.io/thejpster.



[[XJonathanBoccara]]
== Jonathan Boccara

link:sessions.html#X105STLAlgorithmsinLessThananHour[105 STL Algorithms in Less Than an Hour]

Jonathan Boccara is a Principal Engineering Lead at Murex where he works on
large codebases in {cpp}. His primary focus is searching how to make code
more expressive. He has dedicated his blog, Fluent {cpp}, to writing
expressive code in {cpp}. He also gives internal trainings on {cpp} every day,
in the short format called "Dailies".



[[XJonathanMüller]]
== Jonathan Müller

link:sessions.html#XIjustwantedtopointtosomething[I just wanted to point to something!]

Jonathan is a CS student passionate about {cpp}. In his spare time he writes libraries like foonathan/memory which provides memory allocator implementations. He is also working on standardese which is a documentation generator specifically designed for {cpp}. Jonathan tweets at @foonathan and blogs about various {cpp} and library development related topics at foonathan.net.


[[XJonathanWakeley]]
== Jonathan Wakeley

link:sessions.html#XThese10tricksthatonlylibraryimplementorsknow[These 10 tricks that only library implementors know!]

Jonathan is the lead developer of libstdc++, the standard library implementation for gcc.


[[XKateGregory]]
== Kate Gregory

link:sessions.html#XSimplicitynotjustforbeginners[Simplicity: not just for beginners]

Kate Gregory has been using {cpp} for over thirty years. 
She writes, teaches, mentors, codes, and leads projects, primarily in {cpp}. Kate is a Microsoft Regional Director, a Visual {cpp} MVP, has written over a dozen books, and speaks at conferences and user groups around the world. Kate develops courses on {cpp}, Visual Studio, and Windows programming for Pluralsight, is active on over a dozen StackExchange sites, and blogs infrequently.


[[XKevlinHenney]]
== Kevlin Henney

link:sessions.html#XProceduralProgrammingItsBackItNeverWentAway[Procedural Programming: It's Back? It Never Went Away]

Kevlin is an independent consultant, speaker, writer and trainer. His development interests are in patterns, programming, practice and process. He has been a columnist for a number of magazines and sites and has been on far too many committees (it has been said that "a committee is a cul-de-sac down which ideas are lured and then quietly strangled"). He is co-author of A Pattern Language for Distributed Computing and On Patterns and Pattern Languages, two volumes in the Pattern-Oriented Software Architecture series. He is also editor of 97 Things Every Programmer Should Know. He lives in Bristol and online.


[[XLisaLippincott]]
== Lisa Lippincott

link:sessions.html#XTheShapeofaProgram[The Shape of a Program]

Lisa Lippincott designed the software architectures of Tanium and BigFix, two systems for managing large
fleets of computers. She's also a language nerd, and has contributed to arcane parts of the {cpp}
standard. In her spare time, she studies mathematical logic, and wants to make computer-checked proofs of
correctness a routine part of programming.


[[XLouisDionne]]
== Louis Dionne

link:sessions.html#XRuntimePolymorphismBacktotheBasics[Runtime Polymorphism: Back to the Basics]

Louis is a math and computer science enthusiast with interest in {cpp} (meta)programming, functional programming, domain specific languages and related subjects. He is a member of the {cpp} Standards Committee and of the Boost community, where he authored the Boost.Hana metaprogramming library.


[[XLucaMinudel]]
== Luca Minudel

link:sessions.html#XThefantasticfourcodingpatternsofContinuousDelivery[The fantastic four coding patterns of Continuous Delivery]

Luca Minudel is a Lean-Agile Coach & Trainer with 15 years of experience in Lean/Agile and 20+ in professional software delivery.

He is passionate about agility, lean, complexity science, and co-creation.

He contributed to the adoption of lean and agile practices by Ferrari's F1 racing team. For ThoughtWorks he delivered training, coaching, assessments and organisational transformations in top-tier organisations in Europe and the United States. He worked as Head of Agility in 4Finance, and is working as Lean/Agile Coach and Lean/Agile Practice Lead in the financial sector.

Luca is founder and CEO at SmHarter.com, a company that helps organisations turn their way of working into their competitive advantage.


[[XMarshallClow]]
== Marshall Clow

link:sessions.html#XThese10tricksthatonlylibraryimplementorsknow[These 10 tricks that only library implementors know!]

Marshall is the lead developer of lib++, the standard library implementation for LLVM.


[[XMathieuRopert]]
== Mathieu Ropert

link:sessions.html#XCAPIandABIversioning[C++ API & ABI versioning]

I'm a {cpp} expert at Murex and current leader of the {cpp} interest group in the company. My recent work has been focused on making {cpp} more portable by writing a database agnostic SQL API (showed at CppCon last year), a REST framework and providing modern STL features to older compilers on multiple platforms.

I currently live and work in the Paris area where I co-organize the {cpp} French User Group meetups.


[[XMichaelWong]]
== Michael Wong

link:sessions.html#XHeterogeneousProgramminginCtoday[Heterogeneous Programming in C++ today]

Michael Wong

is the Vice President of Research and Development at Codeplay Software, a Scottish company that produces compilers, debuggers, runtimes, testing systems, and other specialized tools to aid software development for heterogeneous systems, accelerators and special purpose processor architectures, including GPUs and DSPs. He is now a member of the open consortium group known as Khronos and is Chair of the {cpp} Heterogeneous Programming language SYCL, used for GPU dispatch in native modern {cpp} (14/17), OpenCL, as well as guiding the research and development teams of ComputeSuite, ComputeAorta/ComputeCPP. For twenty years, he was the Senior Technical Strategy Architect for IBM compilers.

He is the Canadian Head of Delegation to the ISO {cpp} Standard and a past CEO of OpenMP. He is also a Director and VP of ISOCPP.org, and Chair of all Programming Languages for Canada’s Standard Council. He has so many titles, it’s a wonder he can get anything done. He chairs WG21 SG14 Games Development/Low Latency/Financial/Embedded Devices and WG21 SG5 Transactional Memory, and is the co-author of a book on {cpp} and a number of {cpp}/OpenMP/Transactional Memory features including generalized attributes, user-defined literals, inheriting constructors, weakly ordered memory models, and explicit conversion operators. Having been the past {cpp} team lead to IBM’s XL {cpp} compiler means he has been messing around with designing the {cpp} language and {cpp} compilers for twenty-five years. His current research interest, i.e. what he would like to do if he had time is in the area of parallel programming, future programming models for Neural network, AI, Machine vision, safety/critical/ programming vulnerabilities, self-driving cars and low-power devices, lock-free programming, transactional memory, {cpp} benchmark performance, object model, generic programming and template metaprogramming. He holds a B.Sc from University of Toronto, and a Masters in Mathematics from University of Waterloo.

He has been asked to speak/keynote at many conferences, companies, research centers, universities, including CPPCON, Bloomberg, U of Houston, U of Toronto, ACCU, {cpp}Now, Meeting {cpp}, AD{cpp}, CASCON, Bloomberg, CERN, Barcelona Supercomputing Center, FAU Erlangen, LSU, Universidad Carlos III de Madrid, Texas A&M University, Parallel, KIT School, CGO, IWOMP/IWOCL, Code::dive, many {cpp} Users group meetings, Euro TM Graduate School, and Going Native.

He is the current Editor for the Concurrency TS and the Transactional Memory TS.


[[XMichelGrootjans]]
== Michel Grootjans

link:sessions.html#XPlayingwithProjections[Playing with Projections]

Michel Grootjans has been programming since the age of 12. He has programmed strange machines like the TI 99-4A, the Atari 2600, Mac128, HP28, Apple II, Siemens PLC's using languages like Basic, Pascal, C, HyperTalk, Assembler, ... along the way.

His professional experiences includes building enterprise applications for government, chemical plants, telecom, HR, insurance companies, ... in java, C# and ruby.

He's an independent technical agile coach. He coaches agile teams on continuous improvement, trying to find the most productive principles and practices to deliver value for the customer as fast as possible, while aiming for a product that is both flexible and maintainable.



[[XNicolaiJosuttis]]
== Nicolai Josuttis

link:sessions.html#XCTemplatesRevised[C++ Templates Revised]

link:sessions.html#XC17TheBestFeatures[C++17 - The Best Features]

link:sessions.html#XC17inPractice[C++17 in Practice]

Nicolai Josuttis (http://www.josuttis.com) is an independent systems architect, technical manager, author, and consultant. He designs mid-sized and large software systems for the telecommunication, traffic, finance, and manufacturing industries. He is well known in the {cpp} Community for speaking and writing with authority about {cpp} (being the author of 'The {cpp} Standard Library', '{cpp} Templates', and '{cpp}17 - The Complete Guide') but is also an innovative presenter. He is an active member of {cpp} standardization committee for more than 20 years now.


[[XOdinHolmes]]
== Odin Holmes

link:sessions.html#XHowtobepolitetounicorns[How to be polite to unicorns]

Odin Holmes has been programming bare metal embedded systems for 15+ years and as any honest nerd admits most of that time was spent debugging his stupid mistakes. With the advent of the 100x speed up of template metaprogramming provided by {cpp}11 his current mission began: teach the compiler to find his stupid mistakes at compile time so he has more free time for even more template metaprogramming. Odin Holmes is the author of the kvasir::bit library, a DSL which wraps bare metal special function register interactions allowing full static checking and a considerable efficiency gain over the common practice. He is also active in building and refining the tools needed for this task such as the brigand MPL library, the kvasir::mpl. He is currently the embedded chair of the SG14 working group and co-organizer of the embo.io bare metal embedded conference. 


[[XPaulGrenyer]]
== Paul Grenyer

link:sessions.html#XBuildingaTechCommunityintheEastfromalmostNothing[Building a Tech Community in the East from (almost) Nothing]

Paul Grenyer is the CEO at Naked Element, a Norwich based software company. A founder of SyncNorwich and chair and founder at Norfolk Developers and the nor(DEV):con. 


[[XPeterSommerlad]]
== Peter Sommerlad

link:sessions.html#XMockingFramworksconsideredharmful[Mocking Framworks considered, harmful?!]

Prof. Peter Sommerlad is director of IFS Institute for Software at FHO/HSR Rapperswil, Switzerland. Peter is co-author of the books POSA Vol.1 and Security Patterns and contributed to "97 things every programmer should know". His goal is to make software safer and simpler by Decremental Development: Refactoring software down to 10% its size with better architecture, testability and quality and functionality. To reach that goal his team and students created the {cpp} IDE Cevelop. Peter is a member of Hillside, ACM, IEEE Computer Society, SI, ACCU, the ISO {cpp} standardization committee, and MISRA-{cpp} and AUTOSAR-{cpp} guidelines working groups.



[[XPhilNash]]
== Phil Nash

link:sessions.html#XSwiftDrivenDevelopment[Swift Driven Development]

Phil is the author of the test framework, Catch, and also has feet in the Swift, F# and Kotlin worlds. As Developer Advocate at JetBrains He's involved with CLion, AppCode and ReSharper {cpp}


[[XRichardCorden]]
== Richard Corden

link:sessions.html#XHowtoavoidbottleneckswhenconvertingserialcodetomultithreaded[How to avoid bottlenecks when converting serial code to multithreaded]

Richard Corden is a Lead Software Developer at Programming Research. Richard has been developing static analyzers for C and {cpp} for close to 20 years.  Over this time he has been involved in the development of coding standards and is a co-author of MISRA {cpp}, PRQA's High Integrity {cpp} and the RePhrase Coding Standard.


[[XRogerOrr]]
== Roger Orr

link:sessions.html#XNothingisbetterthancopyormove[Nothing is better than copy or move]

Roger has over 30 years experience in IT, using a variety of languages and platforms, working for a number of different companies over the years.
In 1989 he became a contract computer programmer and has successfully managed to remain at the technical end of IT ever since; his
recent work has mostly been in {cpp}, on both Windows and Linux.

Roger has been a member of ACCU since 1999; he's on the ACCU committee, the ACCU conference committee, the Overload review team and runs the Code Critique section of CVu.
He also writes the occasional article for CVu and Overload.

He is a member of the BSI {cpp} panel, catchily known as IST/5/-/21, and has represented the UK at {cpp} ISO standards meetings since 2010.


[[XRosemaryFrancis]]
== Rosemary Francis

link:sessions.html#XBestpracticeswhenaccessingBigDataoranyotherdata[Best practices when accessing Big Data or any other data!]

.Dr Rosemary Francis is an expert in I/O profiling and high-performance computing with a PhD in Computer Architecture from the University of Cambridge. She is a regular speaker at conferences including IEEE and Linux foundation events and sits on the advisory board for the Ideaspace startup accelerator and the Raspberry Pi foundation. Rosemary founded Ellexus, the I/O profiling company, after working in the semiconductor industry. Today Ellexus provides unique application and cluster monitoring tools to commercial and research organisations around the world, helping them to optimise their applications and manage their IT infrastructure. 


[[XSamathyBarratt]]
== Samathy Barratt

link:sessions.html#XUptoSpeedSuggestionstowardbetteronboardingdocumentation[Up to Speed - Suggestions toward better on-boarding documentation]

Samathy Barratt is a passionate technologist and LGBTQ+ Activist.

Her primary interests lie in highly technical software engineering, new & cutting edge computer science practices, new software tools, languages and cutting edge hardware. 

Samathy thoroughly loves to share with others. She loves the concept of free and open source software and will take any chance she can to help others learn and improve themselves.

She currently studies a BSc at Coventry University.


[[XSchalkCronjé]]
== Schalk Cronjé

link:sessions.html#XBuildingModernNativeApplicationswithGradle[Building Modern Native Applications with Gradle]

Schalk Cronjé has spent many years developing and testing software in a vriety of languages. He has a special affection for automation and buld tooling.

Today he is recognised as one of the most knowledgeable people in the Gradle build tools community that is not an employee of Gradle Inc.  He has spoken widely on the application of Gradle, written a number of guides and is also the author of Idiomatic Gradle Vol 1 & 2 which is available from Leanpub

He is the creator of many open-source projects and contributor to a number more. He serves on the steering committee of the Agile Testing Alliance and is a board member of DevOps++ Alliance in Europe.

He lives in and works from the small Principality of Andorra in the Pyrenees mountains.



[[XSebRose]]
== Seb Rose

link:sessions.html#XSoftwaredevelopmentlearningtowalkagain[Software development – learning to walk again]

Seb has been involved in the full development lifecycle with experience that ranges from Architecture to
Support, from BASIC to Ruby. He’s a partner in Cucumber Limited, who help teams adopt and refine their agile
practices, with a particular focus on collaboration and automated testing.

Regular speaker at conferences and occasional contributor to software journals. Co-author of “BDD Books 1:
Discovery” (LeanPub), lead author of “The Cucumber for Java Book” (Pragmatic Programmers), and contributing
author to “97 Things Every Programmer Should Know” (O’Reilly).

He blogs at cucumber.io and tweets as @sebrose.


[[XSergeyIgnatchenko]]
== Sergey Ignatchenko

link:sessions.html#XMultiCoringandNonBlockinginsteadofMultiThreadingorusingReActorstobuildScalableInteractiveDistributedSystems["Multi-Coring" and "Non-Blocking" instead of "Multi-Threading", or using (Re)Actors to build Scalable Interactive Distributed Systems]

Sergey has 20+ years of software development experience, including 15+ years of experience in architectural positions. Among other things, he was a co-architect of a G20 online stock exchange, and a sole architect of a major online game with 400K+ simultaneous players. He's also known for his articles in CUJ, {cpp} Report, and Overload, as well as for his blog ithare.com; he also spoke at ACCU and CPPCON, and successfully Kickstarted his upcoming 9-volume book "Development & Deployment of Multiplayer Online Games".


[[XStephenKelly]]
== Stephen Kelly

link:sessions.html#XEmbracingModernCMakeLibraryDependenciesandPackages[Embracing Modern CMake – Library Dependencies and Packages]

Stephen Kelly has been working with {cpp} as a Software Engineer for 10 years. After starting out contributing to KDE applications and libraries, he subsequently became focused on the dependencies of KDE. 

This took him on a journey of contributing for many years to Qt and CMake, and integrating the two in a way which was innovative at the time, but seems obvious now.

Stephen eventually progressed further up the stack to follow compiler development more closely via Clang, and {cpp} development via isocpp proposals.

Stephen lives in Dublin, works at Havok and likes running.



[[XSteveHolden]]
== Steve Holden

link:sessions.html#XHowPythonWinsNewFriends[How Python Wins New Friends]

Steve has been using Python for twenty years, having used many other languages from Algol 60 to Z80 assembly language, taking in FORTRAN, C and various BASICs along the way.

An enthusiastic presenter and an advocate for the Python language, Steve wrote "Python Web Programming" in 2002, and is an author of the recently published third edition of "Python in a Nutshell."


[[XTimurDoumler]]
== Timur Doumler

link:sessions.html#XClassTemplateArgumentDeductioninC17[Class Template Argument Deduction in C++17]

Timur Doumler develops software at JetBrains, where he currently works on CLion, the cross-platform {cpp} IDE. In the past he has worked in the audio tech industry and has written code for JUCE, the popular open-source cross-platform {cpp} framework for building desktop and mobile audio apps. Timur holds a PhD in astrophysics and is passionate about clean code, low-latency performance and {cpp} standardisation.


[[XUbertoBarbini]]
== Uberto Barbini

link:sessions.html#XAlchemicalCodeRejuvenation[Alchemical Code Rejuvenation]

Uberto is an expert on designing and building software products, currently working with finance institutions in London using Haskell and Java.
He has more than two decades experience, in many industries in building great sw products. He is practicing TDD and Agile since 2001.
He writes technical articles, regularly speaks at conference around Europe and organises courses.
Last but not least he is a passionate polyglot programmer, he started as a kid with a ZxSpectrum he hopes to continue for many years to come.

https://www.slideshare.net/ubertobarbini/presentations

https://medium.com/@ramtop


[[XValentinGalea]]
== Valentin Galea

link:sessions.html#XTheBadlandsofCProfessionalGameDevelopment[The Badlands of C++: Professional Game Development]

Valentin Galea is a professional video game developer based in London, UK. He currently works at Splash Damage for the award-winning "Gears of War" franchise on Windows 10 and Xbox One. {cpp} enthusiast and evangelist, focused on systems, graphics and engine programming. He has more than 10 years worth of experience, with past work ranging from MMO projects to mobile and handheld games. When he's not geeking out on games, he collects vinyl records.


[[XVictorCiura]]
== Victor Ciura

link:sessions.html#XBootstrappingaLocalCUserGroup[Bootstrapping a Local C++ User Group]

Victor Ciura is a Senior Software Engineer at CAPHYON and Technical Lead on the Advanced Installer team (http://www.advancedinstaller.com). 
For over a decade, he designed and implemented several core components and libraries of Advanced Installer such as: IIS, Repackager, OS virtualization and others. 

He’s a regular guest at Computer Science Department of his Alma Mater, University of Craiova, where he gives student lectures & workshops on “Using {cpp}STL for Competitive Programming and Software Development”. 

Currently, he spends most of his time working with his team on improving and extending the repackaging and virtualization technologies in Advanced Installer IDE, helping clients migrate their Win32 desktop apps to the Windows Store (AppX).


[[XVigneshwerDhinakaran]]
== Vigneshwer Dhinakaran

link:sessions.html#XHackersguidetoRustProgramming[Hacker's guide to Rust Programming]

link:sessions.html#XHackersguidetoWebAssembly[Hacker's guide to Web Assembly]

Vigneshwer is an innovative data scientist from Bengaluru who crunches real-time data and builds AI algorithms for complex business problems. He believes that technology needs to have a human-centric design to cater solutions to a diverse audience. He’s an official Mozilla TechSpeaker, and is the author of Rust Cookbook.



[[XVittorioRomeo]]
== Vittorio Romeo

link:sessions.html#XZeroallocationandnotypeerasurefutures[Zero-allocation & no type erasure futures]

Vittorio is a software engineer at Bloomberg L.P. with a BS in Computer Science from "Università degli Studi di Messina". He began programming at a very young age and is now a {cpp} enthusiast. While following and participating in the evolution of the {cpp} Standard and embracing the newest features, he worked on several open-source projects, including modern general-purpose libraries and free cross-platform indie games. Vittorio is an active member of the {cpp} community: he participated as a speaker at CppCon, {cpp}Now, Meeting {cpp}, ACCU, and ++it Florence. He currently maintains a technical blog revolving around {cpp}, several open-source projects, and a YouTube channel featuring modern {cpp} tutorials. When he's not writing code, Vittorio enjoys weightlifting and fitness-related activities, competitive computer gaming and sci-fi movies/TV-series.



[[XWojciechBasalaj]]
== Wojciech Basalaj

link:sessions.html#XHowtoavoidbottleneckswhenconvertingserialcodetomultithreaded[How to avoid bottlenecks when converting serial code to multithreaded]

Wojciech Basalaj graduated from King’s College, London with a First Class BSc degree in Computer Science in 1997. As part of the course, he undertook a one-year industrial placement at Lucent Technologies Wireless in Winchester. Wojciech obtained his Ph.D. in the field of Information Visualization at Trinity College, Cambridge in 2000. Since then he works for PRQA, initially in the Consulting Services Group, and for the last 8 years as a Senior Developer, working on static code analysis.

