////
.. title: Lead Presenter Deals
.. type: text
////

ACCU conferences have 90 minute (and occasionally 180 minute) and 20 minute sessions, and there are full-day
pre-conference tutorials. It is not currently possible to offer presenters of 20 minute sessions a deal,
though we hope we will be able to in future ACCU conferences. Lead presenters of 90 (and 180) minute
sessions, and leads of the pre-conference tutorials are offered the following deals.

For full details, or if you have specific concerns regarding affordability, please email accu@archer-yates.co.uk


== Lead Presenters of Conference Sessions

Lead presenters of 90 and 180 minute conference sessions are offered:

* Free attendance at the conference.
* Free admission to the conference dinner.
* Two nights accommodation at the conference hotel.
* Remuneration of reasonable travel expenses.

Where presenters are able to recover costs from elsewhere, we (obviously) encourage this as it lowers the
pool of presenters claiming. This allows us to be much more flexible in supporting those presenters who are
reliant on reclaiming their costs to be able to get to the conference.


== Lead presenters of Pre-conference Workshops

Lead presenters of the 6 hour pre-conference workshops are offered:

* Two nights accommodation at the conference hotel.
* Remuneration of reasonable travel expenses.
* A fee.
* Free attendance at the conference.
* Free attendance at the conference dinner.
